guests = ['Niel deGrasse Tyson', 'Theodore Roosevelt', 'George Washington']
print(f"Dear, {guests[0]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[1]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[2]} a seat has opened in my feast would you accept thing invitation?. \nFrom, Anthony Frederick")
print("\nGeorge Washington couldn't make it as he has a war to attend to")
del(guests[2])
print(f"\nDear, {guests[0]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"Dear, {guests[1]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print("\n Turns out we have a bigger table then I thought so I invited more guests")
guests.insert(0, 'Michael Phelps')
guests.insert(2, 'Martin Luther King Jr.')
guests.insert(4, 'Abraham Lincoln')
print(f"\nDear, {guests[0]} if you aren't busy please come to join my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[1]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[2]} I would be pleased to have you at my dinner!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[3]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[4]} a seat has opened in my feast would you accept thing invitation?. \nFrom, Anthony Frederick")

