guests = ['Niel deGrasse Tyson', 'Theodore Roosevelt', 'George Washington']
print(f"Dear, {guests[0]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[1]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[2]} a seat has opened in my feast would you accept thing invitation?. \nFrom, Anthony Frederick")
print("\nGeorge Washington couldn't make it as he has a war to attend to")
del(guests[2])
print(f"\nDear, {guests[0]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"Dear, {guests[1]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print("\n Turns out we have a bigger table then I thought so I invited more guests")
guests.insert(0, 'Michael Phelps')
guests.insert(2, 'Martin Luther King Jr.')
guests.insert(4, 'Abraham Lincoln')
print(f"\nDear, {guests[0]} if you aren't busy please come to join my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[1]} you have been invited to my dinner. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[2]} I would be pleased to have you at my dinner!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[3]} come join me for dinner and have a great time!. \nFrom, Anthony Frederick")
print(f"\nDear, {guests[4]} a seat has opened in my feast would you accept thing invitation?. \nFrom, Anthony Frederick")
print("\nTurns out the table is going to arrive later then we thoguht sorry everyone.")
uninvited = guests.pop(0)
uninvited2 = guests.pop(1)
uninvited3 = guests.pop(2)
print(f"\nSorry {uninvited} we have to revoke your invitation due to space.")
print(f"\nSorry {uninvited2} we have to revoke your invitation due to space.")
print(f"\nSorry {uninvited3} we have to revoke your invitation due to space.")
print(f"\n{guests[0]} you are still invited")
print(f"\n{guests[1]} you are still invited")
del(guests[1])
del(guests[0])
print(guests)